//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.28 at 04:07:53 PM CEST 
//


package it.objectway.jaxb.address;

import javax.xml.bind.annotation.XmlRegistry;
import it.objectway.jaxb.address.ObjectFactory;
import it.objectway.jaxb.address.UsOrCanadaAddress;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.objectway.jaxb.address package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.objectway.jaxb.address
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UsOrCanadaAddress }
     * 
     */
    public UsOrCanadaAddress createUsOrCanadaAddress() {
        return new UsOrCanadaAddress();
    }

}
