//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.24 at 03:11:33 PM CEST 
//


package it.objectway.jaxb.callback.internal;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for journalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="journalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}article" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journalType", propOrder = {
    "article"
})
public class JournalType {

    protected List<ArticleType> article;

    /**
     * Gets the value of the article property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the article property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleType }
     * 
     * 
     */
    public List<ArticleType> getArticle() {
        if (article == null) {
            article = new ArrayList<ArticleType>();
        }
        return this.article;
    }
    
    private void beforeUnmarshal(Unmarshaller unmarshaller, Object parent){
    	String parentString = " , parent = ";
    	if(parent!=null){
    		parentString = parentString + parent.getClass().getName();
    	}
    	System.out.println("beforeUnmarshal: oggetto corrente " + this.getClass().getName() + parentString);
    }
    
    private void afterUnmarshal(Unmarshaller unmarshaller, Object parent){
    	String parentString = " , parent = ";
    	if(parent!=null){
    		parentString = parentString + parent.getClass().getName();
    	}
    	System.out.println("afterUnmarshal: oggetto corrente " + this.getClass().getName() + parentString);
    }
    private void beforeMarhshal(Marshaller marshaller){
    	 
    	System.out.println("beforeMarhshal: oggetto corrente " + this.getClass().getName());
    }
    private void afterMarhsal(Marshaller marshaller){
    	
    	System.out.println("afterUnmarshal: oggetto corrente " + this.getClass().getName() );
    }
}
